version: '3.9'
networks:
  freddy:

services:
  java:
    image: openjdk:16
    networks:
        - freddy
    restart: unless-stopped
    volumes:
        - ./bot/start.sh:/start.sh
        - ./bot/gradle:/gradle
        - ./bot/gradlew:/gradlew
        - ./bot/build.gradle:/build.gradle
        - ./bot/settings.gradle:/settings.gradle
        - ./bot/src:/src
    working_dir: /
    entrypoint: ['./start.sh']
    container_name: freddy_dev
    profiles:
      - dev
    env_file:
      - ./bot/settings.env
  freddy:
    image: ghcr.io/driedsponge/freddy:latest
    networks:
      - freddy
    restart: unless-stopped
    container_name: freddy_prod
    profiles:
      - prod
    env_file:
      - ./bot/settings.env

